<a href="https://colab.research.google.com/github/nikhil2008github/Data-ops/blob/main/numpy_function_and_syntax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **numpy function and syntax**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
a = np.array([5,6,7]) # This how a array is define 
a

array([5, 6, 7])

In [ ]:
a.ndim # this function define the dimention of arry 

1

In [ ]:
a.itemsize #it define the size of array 

8

In [ ]:
a.size # count of item in aaray 


3

In [ ]:
a.shape #define the shape of array 

(3,)

In [ ]:
a = np.array ([[1,2],[3,4],[5,6]]).dtype # define the type of array 
a

dtype('int64')

In [ ]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
   

In [ ]:
  np.zeros((2,3), dtype=int) # help to gernerat a array with initilizing zero 

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
  np.ones((2,3), dtype=int) # help to gernerat a array with initilizing ones

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
a= np.arange(1,17,2) #arange([start,] stop[, step,], dtype=None, *, like=None)
#Examples
# >>> np.arange(3)
# array([0, 1, 2])
# >>> np.arange(3.0)
# array([ 0.,  1.,  2.])
# >>> np.arange(3,7)
# array([3, 4, 5, 6])
# >>> np.arange(3,7,2)
# array([3, 5]
a


array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [ ]:
np.linspace(1,5,10) # it is used to generate the no between given numbers 

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
a.reshape(8,1) # it is use to reshape the array 

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15]])

In [ ]:
a

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [ ]:
a.ravel() # it is used to flatten the aaray 
a

array([ 1,  3,  5,  7,  9, 11, 13, 15])

## Function of math

In [ ]:
a = np.array ([[1,2],[3,4],[5,6]])
b = np.array ([[7,8],[9,10],[11,12]]) 

In [ ]:
a.min() # to print min

1

In [ ]:
a.max() # to print max element

6

In [ ]:
a.sum() # to print sum of array 

21

In [ ]:
a = np.array ([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a.sum(axis =1) # to print the sum of row

array([ 3,  7, 11])

In [ ]:
a.sum(axis =0) # to print the sum of column

array([ 9, 12])

In [ ]:
np.sqrt(a) # to find the square root of arrsy of a 

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [ ]:
a = np.array ([1,2,3,4,5,6,7,8,9])

# Indexing and slicing

In [ ]:
a[0:5]

array([1, 2, 3, 4, 5])

In [ ]:
a = np.array ([[1,2],[3,4],[5,6]])

In [ ]:
a[0:2]

array([[1, 2],
       [3, 4]])

In [ ]:
a[0:4,0] # this is use to how many item you want to print 

array([1, 3, 5])

# Iterate through Array 

In [ ]:
a = np.array ([1,2,3,4,5,6,7,8,9])